enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEFAULT"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
skylorlib = true
angelblockrenewed = true
farmersdelight = true
seasonsextras = true
forgottengraves = true
sihywtcamd = true
spectrum = true
lightwithin = true
pfm = true
betternether = false
immersive_portals = true
eldritch_mobs = true
betterend = true
friendsandfoes = true
bitsandchisels = true
enhancedcelestials = true
snowyspirit = true
wireless-redstone = true
origins = true
magistuarmory = true
halfdoors = true
milk = true
minecarttweaks = true
chunkloaders = true
charm = true
soundmuffler = true
graveyard = true
treechop = true
hexxitgear = true
customportalapi = true
naturalist = true
ironchests = true
oreberries = true
lava_walker = true
techreborn = true
indrev = true
deeperdarker = true
beachparty = true
terrestria = true
create = true
dimdoors = false
minecraft = true
philipsruins = true
chococraft = true
twilightforest = true
ae2 = true
paradise_lost = true
waystones = true
adventurez = true
computercraft = true
moderndynamics = true
traverse = true
itemalchemy = true
soulshards = true
universal_graves = true
kibe = true
ad_astra = true
enchantinginfuser = true
rechiseled = true
mysticaloaktree = true
